---
# tasks/playbook_install_apt_packages.yaml
# Author: Micah Bronfman
# Purpose: Install apt packages on Cloud VMs (excluding Docker)

- name: "Update apt cache"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: "Install required apt packages"
  apt:
    name:
      - default-jdk
      - python3        
      - python3-pip      
      - git               
      - gcc          
    state: present
